### ISSUE TITLE
Error if DocType and View don't have the same name.

### ISSUE THREAD

**Issue by c9mbundy** [umco/umbraco-doc-type-grid-editor#143] opened 2019-05-23 01:57 UTC
Suppose DocType is: MyDocType_2 and is using a common ViewTemplate:  MyDocType

At the moment I get an error along the lines of:

`System.InvalidOperationException: The partial view 'MyDocType_2' was not found ... etc etc` 

Error is being generated from DocTypeGridEditor.cshtml presumably because the ConvertValueToContent helper is assuming DocType and ViewTemplate names are the same?

**Comment by cdecinkoKnight** [comment] 2019-05-23 20:09
Same issue here.  Also, it fails to find the template if it's in a subfolder and not in the root partials folder.

**Comment by leekelleher** [comment] 2019-05-25 11:19
Hey @c9mbundy @cdecinkoKnight, DTGE will attempt to locate partial-views based on the grid-editor's alias, then fallback on the DocType's alias, then fallback on a "Default.cshtml" _(that can be specified in the `viewPath` config)._

If those don't match a partial-view, then the fallback is to use ASP.NET MVC's `Html.Partial()` - first with the grid-editor alias, then the DocType alias.

If you need to use a different partial-view, like in the case of `MyDocType_2`, you could make a partial-view with that name, then call `@Html.Partial("MyDocType")` from there? _(in order to reuse the original partial-view)_

As for sub-folders, you could try changing the `viewPath` value in the DTGE's grid-editor config?

---

Alternatively, if you need advanced control of the partial-views - you could change the DTGE's "`render`" in the grid-editor JSON config file?
The default render partial-view is [`DocTypeGridEditor.cshtml`](https://github.com/umco/umbraco-doc-type-grid-editor/blob/0.6.1/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml), you could swap that out for something else and manipulate it however you like.

---
I'll close this ticket off, as it's not a bug per-se - it's configurable. 👍

**Closed by leekelleher** 2019-05-25 11:19 UTC
