### ISSUE TITLE
With preview mode off, the Grid just shows "Doc Type" whenever this package is used

### ISSUE THREAD

**Issue by HarveyWilliams** [umco/umbraco-doc-type-grid-editor#62] opened 2017-01-17 13:46 UTC
With preview mode off, the Grid just shows "Doc Type" whenever this package is used in the grid. Picture attached showing this:

![doctype](https://cloud.githubusercontent.com/assets/7733459/22022664/d1db0f28-dcba-11e6-91ad-a7cd22bb4761.png)

Changing line 23 in the `doctypegrideditor.controllers.js` to write:

```
$scope.title = $scope.control.value.dtgeContentTypeAlias;
```

Instead of:

```
$scope.title = $scope.control.value.value.name;
```

Partially improves this issue, as shown below:

![grideditormap](https://cloud.githubusercontent.com/assets/7733459/22022762/3d57b4ea-dcbb-11e6-8461-0a2b54338a7e.png)

This is slightly better as it shows what is being rendered to the user rather than just writing a generic name.

Can I just check there isn't a better solution to this problem?

**Comment by leekelleher** [comment] 2017-01-17 13:57
@HarveyWilliams The words "Doc Type" is coming from the "name" of whatever grid-editor is defined in the [`grid.editors.config.js`, see line 2](https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Config/grid.editors.config.js#L2).  Our recommendation is to make your own grid-editor definitions, then you can name them accordingly.

**Comment by leekelleher** [comment] 2017-02-19 21:39
Closing issue, this is intended behaviour.

@HarveyWilliams - I've recently added in some nicer CSS styles - they're commented out at the moment, but you might like them? [See doctypegrideditor.css, line 16](https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Css/doctypegrideditor.css#L16).

**Closed by leekelleher** 2017-02-19 21:39 UTC

**Comment by HarveyWilliams** [comment] 2017-02-21 11:17
@leekelleher Nice those styles make it much prettier, thanks!

Otherwise in the future I'm just gonna put more effort into making the previews work. :)
