### ISSUE TITLE
DTGE with a grid editor, selecting a row type closes the dialog

### ISSUE THREAD

**Issue by clarkd** [umco/umbraco-doc-type-grid-editor#95] opened 2018-03-07 17:09 UTC
We are using DTGE with a doctype that contains a grid editor. When the user selects a row for the grid the whole dialog disappears.

While the nesting of a grid within a grid seems a bit weird it allows a specific use case for us. It's a grid editor called "Expanding Content" which renders a button with some content collapsed - the user can view/expand the content by clicking the button. The content needs to be dynamic so we utilise a grid editor so the editor can add any content as they wish. 

![dtge](https://user-images.githubusercontent.com/3793131/37106655-48c0d25c-222a-11e8-8702-2547f7b0241d.gif)

This previously worked with an earlier release of DTGE/Umbraco but since upgrading these we've seen the above issue.

Happy to help / submit a PR but not too sure where to start as there is no console errors etc.

**Comment by leekelleher** [comment] 2018-03-07 18:22
Hi @clarkd - I can only assume this is related to the recent change from using the (old) dialog panel to the (newer) overlay modal (docked right).  I'm not sure what would be triggering the overlay to close here, (as I've never tried a Grid-within-a-Grid before).

My gut feeling would be that the code triggering the closing overlay is from the Grid's "Add row" button, but you'd need to investigate further.

**Comment by clarkd** [comment] 2018-03-07 21:09
Hi @leekelleher, thanks for your reply.

Would you suggest any alternative to the grid within a grid method?

In the meantime I'll try and take a look at the code behind the row selection!

**Comment by EllaKreal** [comment] 2018-06-13 14:16
No idea if this helps but a quick/dirty workaround is commenting out `$scope.showRowConfigurations = false;` in umbraco.controller.js (Line 12276 in mine) - it stops the panel from closing, but means the row options remain and do not revert to the + button once you add a row to any grid.

**Comment by skttl** [comment] 2018-09-04 19:45
I think this happens, because the "template" is a `div`. Umbraco has some code that closes the dialog on clicks outside (for some reason, it sometimes thinks elements inside the overlay is outside, that is probably the root cause), and in that code it excludes all clicks on elements of the types `a`, `input` and `button`.

So the simple fix (for Umbraco) is to change the template to a `button`, or something else. Which also benefits accessibility, as they natively have clickhandlers, you can tab to them etc....

**Comment by skttl** [comment] 2018-10-22 18:35
I added an issue for Umbraco, going to do a PR in the coming days :)

**Comment by leekelleher** [comment] 2018-12-13 14:13
Closing off this ticket... issue & PR are submitted to Umbraco core.

- https://github.com/umbraco/Umbraco-CMS/issues/3391
- https://github.com/umbraco/Umbraco-CMS/pull/3407

**Closed by leekelleher** 2018-12-13 14:13 UTC
Labels: cant-fix, umbraco
