### ISSUE TITLE
Provide access to containing Page

### ISSUE THREAD

**Issue by arknu** [umco/umbraco-doc-type-grid-editor#54] opened 2016-10-20 09:44 UTC
The `DetachedPublishedContent` type has an internal property called `_containerNode`. It would be very useful to have access to this property from the view so that you can do things relative to the current page.

**Comment by leekelleher** [comment] 2016-10-20 12:20
@arknu Thanks for raising this.

The problem is with how to expose the `_containerNode` value, and still be a valid `IPublishedContent`? (Believe me, we've discussed this a lot! 😃)

In the meantime, as a workaround you can try using `UmbracoContext.Current.PageId` to get the ID of the current page.  If you're using a controller, (inheriting from `DocTypeGridEditorSurfaceController`), then you will have access to the `CurrentPage` property.

**Comment by leekelleher** [comment] 2016-12-05 10:36
Closing this one; workaround answer provided.

**Closed by leekelleher** 2016-12-05 10:36 UTC
Labels: question
