### ISSUE TITLE
Issues while upgrading from version 0.21 

### ISSUE THREAD

**Issue by gripusa** [umco/umbraco-doc-type-grid-editor#77] opened 2017-06-29 13:33 UTC
We are trying to upgrade the plugin from 0.21 to latest version . However, we are getting following exception. 

```
Method not found: 'System.Web.Mvc.ActionResult Our.Umbraco.DocTypeGridEditor.Web.Controllers.DocTypeGridEditorSurfaceController`1.CurrentPartialView(System.Object)'.
System.MissingMethodException: Method not found: 'System.Web.Mvc.ActionResult Our.Umbraco.DocTypeGridEditor.Web.Controllers.DocTypeGridEditorSurfaceController`1.CurrentPartialView(System.Object)'.
   at {ProjectName}.Web.Controllers.SurfaceControllers.SectionSurfaceController.Section()
```

**Comment by leekelleher** [comment] 2017-06-29 13:46
Hi @gripusa,

I'm not sure why that error would be caused, the controller method is definitely still there in v0.4.0.

<https://github.com/umco/umbraco-doc-type-grid-editor/blob/0.4.0/src/Our.Umbraco.DocTypeGridEditor/Web/Controllers/DocTypeGridEditorSurfaceController.cs#L34>

Just checking is the "Our.Umbraco.DocTypeGridEditor.dll" in your /bin folder?

As a last resort, you may need to recompile your code against the latest DLL?

**Comment by gripusa** [comment] 2017-06-29 14:31
Hi Leekelleher,
Thanks for coming back to me. I verified the dll updates in "bin" then i also verified by checking the definition and i can see the method there. The exception is thrown when it tries to render the view from DataTypeGridEditor View. 
Few more info on it. If i setup a break point in the action method, i never reach to it, however, the breakpoint in my surfacecontroller's contrsuctor is hitting.

**Comment by gripusa** [comment] 2017-06-29 14:51
Now, I just upgraded the solution to latest version of Umbraco and then applied the upgrade to DTGE and i am seeing the following error on the front-end. (We can see the editor and content fine on the backend for now) 
System.Exception: Exception while creating a value. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Models.PublishedContent.PublishedContentType.Get(PublishedItemType itemType, String alias)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.<>c__DisplayClassc.<GetContentTypesByAlias>b__b()
   at Umbraco.Core.Cache.DictionaryCacheProviderBase.<>c__DisplayClass1.<GetSafeLazy>b__0()
   --- End of inner exception stack trace ---
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String contentTypeAlias, String dataJson)
   at ASP._Page_app_plugins_doctypegrideditor_render_doctypegrideditor_cshtml.Execute() in {projectpath}\App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditor.cshtml:line 26
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Partials_grid_editors_base_cshtml.Execute()

**Comment by gripusa** [comment] 2017-07-03 14:24
As discussed above, although we can see the content in back-office but we are still unable to see the content on the front-end. 
Another issue is that if we publish a page which has existing grid content, it looses all of its grid contents. 
Upon further investigation, it seems to be a problem of older version using GUID for content storage vs the new version relying on alias. 
We have tested that new content on the same website is publishing and showing the content on the front-end site pretty fine. 

So is there any migration scenario exist through which we can migrate this existing content? It will be beneficial to have a script to upgrade the older version into the newer version if it was kind of breaking change. (Please let us know if we have to pay for this as i understand it may be beyond the remit of what is available as of now)

**Comment by leekelleher** [comment] 2017-11-13 17:58
Hi @gripusa - sorry for not following up on this, (it's been a busy few months - I moved house, amongst other things).

Can I check if you also upgraded Umbraco at the same time? As I recall with Umbraco 7.3, all the DocType GUIDs were regenerated & normalized during the upgrade. I suspect this what you may have experienced here.  What did you end up doing with the existing content? (I'd hate to think that the content was lost 😕)

**Comment by leekelleher** [comment] 2018-02-21 11:26
Closing this issue.

I suspect the issue is due to the order of upgrading, DTGE would need to have been upgraded before upgrading Umbraco (through the v7.4.0 release), as the doctype Guids are all regenerated in an upgrade migration.  Which would mean that the data in the older versions of DTGE wouldn't be able to find the corresponding doctype.

> For more details about this, please see the Umbraco issue [#U4-7286](http://issues.umbraco.org/issue/U4-7286) and [v7.4.0 migration script](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenFourZero/EnsureContentTypeUniqueIdsAreConsistent.cs).

If you feel this is still an issue, please feel free to re-open.

**Closed by leekelleher** 2018-02-21 11:26 UTC
Labels: umbraco
