### ISSUE TITLE
$scope.control.editor.config is null after save & publish

### ISSUE THREAD

**Issue by Nikos-Sid** [umco/umbraco-doc-type-grid-editor#84] opened 2018-01-14 12:44 UTC
Hi,
I am using docType grid editor v0.4.0 and Umbraco 7.7.6.
Once i save and publish the node and i try to click on an item in the doc type grid to edit it, 
the dtgeDialogService.open is called but the $scope.control.editor is undefined.
This only happens when the grid is nested in a vorto property, at least in my case
Any ideas?

**Comment by leekelleher** [comment] 2018-12-13 14:23
Closing off this ticket.  @Nikos-Sid apologies for not responding to it when you opened it. I don't have much experience with using Vorto, so wasn't sure what to suggest. What did you end up doing with it?

If the issue persists and you can help identify the cause, I'd be happy to re-open the ticket.

**Closed by leekelleher** 2018-12-13 14:23 UTC
Labels: question, up-for-grabs

**Comment by marcond05** [comment] 2019-05-10 17:29
I'm not sure if this can be reopened, but we have had this issue for some time as well.. Had some spare time and thought I'd see about fixing it. You are only able to save & publish once. After Save & Publish, if you then click on a Widget (a DTGE) it will result in the following errors: 
![image](https://user-images.githubusercontent.com/8170842/57544497-80005380-7325-11e9-89d4-d4cee54454e6.png)

You actually don't have to edit the DTGE's at all, just hit save & publish and attempt to open a DTGE modal it will crash. The general schema we have is 

Content Node -> Nested Content Item -> Umbraco Grid  -> DTGE items inside various cells

I'm going to continue poking around the source here, but after adding some logs the $scope.model is indeed missing all the goods (screenshot below). 

Lee, was wondering if you had any other ideas on things to try? 

![image](https://user-images.githubusercontent.com/8170842/57545168-88f22480-7327-11e9-94c5-1402403cc228.png)

**Comment by leekelleher** [comment] 2019-05-13 08:11
@marcond05 If you could open a separate issue ticket for this, that'd be great.

Forewarning, while I'm still supporting DTGE as a package, I haven't actively used it myself in the past few years, so I may not be familiar with the nested approach that you are attempting here, _(i.e. The Grid within Nested Content - I never tried that)_.

**Comment by marcond05** [comment] 2019-05-13 17:24
Hi Lee, 

Yea no worries at all, thank you for replying. I have created a new issue as you requested.  #140 

If the extra context is helpful, we use nested content to represent actual <section> tags in our content. We found it nearly impossible to properly express all the abilities of Bootstrap 4 & flexbox grids within Umbraco due to how the grid is currently designed. So we loop through our Content Strips and each NC has a corresponding View doctypeAlias.cshtml , then in those views we're rendering grids (where applicable). Image galleries, various types of grids, etc. 

It's been easier on our editors, but ultimately I think a new grid is needed soon. Perhaps we'll roll our own solution soon, but for now DTGE has been a savior for us, so thanks again Lee!

-Marc
